"""discovery_scheduler.py — dynamic opportunity discovery scheduler (v2.0.36f).

Decides, from HISTORICAL PERFORMANCE, which sources to search, when, how often, which categories to
prioritize, which searches to reduce, which sources to suspend, and which new sources to explore.
Maintains an exploration/exploitation balance so known winners are NOT fully exploited.

Respects (deterministic — the LLM is never in this path):
- platform rate limits     -> delegated to platform_throttle.acquire() at execution
- source cooldowns         -> per-source min interval
- resource constraints     -> max_tasks_per_tick / max_concurrent
- model availability       -> LLM-generated strategies skipped if model unavailable
- configured working hours -> skip ticks outside the window
- opportunity freshness    -> only re-search categories older than freshness_window
- duplicate detection      -> DiscoveryEngine dedup
- source reliability       -> from earning_memory source_memory / platform_reputation
- error backoff            -> exponential suspension on repeated errors (recovers; ONE bad result
                              does NOT permanently kill a source)

Security: the scheduler only ever drives VALIDATED provider interfaces (DiscoveryEngine sources).
The LLM is never given a network/external action here. Search strategies are generated by
discovery_strategies.SearchStrategyGenerator (LLM = optional suggestion source, fails safe).
"""

from __future__ import annotations

import math
import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from agents.discovery_strategies import SearchStrategyGenerator, SearchStrategy


# Exploration floor: at least this fraction of each tick's tasks must be exploration,
# so the system does not collapse into pure exploitation of known winners.
EXPLORATION_FLOOR = 0.20

# How much a reliable+profitable source shortens its interval (multiplier on base).
EXPLOIT_INTERVAL_MULT = 0.5
# How much a low-yield/high-error source lengthens its interval.
REDUCE_INTERVAL_MULT = 2.5
# Base re-search interval (seconds) per source when no history.
BASE_INTERVAL = 1800.0  # 30 min
# Minimum interval regardless of how good a source is.
MIN_INTERVAL = 300.0    # 5 min
# Maximum interval (source effectively deprioritized but not dead).
MAX_INTERVAL = 21600.0  # 6 h


@dataclass
class SourceState:
    name: str
    last_run: float = 0.0
    interval: float = BASE_INTERVAL
    error_count: int = 0
    suspended_until: float = 0.0
    success_count: int = 0
    yield_count: int = 0
    priority: float = 1.0

    def is_suspended(self, now: float) -> bool:
        return now < self.suspended_until

    def backoff_seconds(self, base: float = 600.0) -> float:
        # exponential: base * 2**error_count, capped.
        return min(base * (2 ** self.error_count), 86400.0)


@dataclass
class DiscoveryTask:
    source: str
    strategy: Optional[SearchStrategy]
    category: str
    priority: float
    is_exploration: bool
    reason: str


@dataclass
class SchedulerConfig:
    working_hours: Optional[Tuple[int, int]] = None   # (start_hour, end_hour) local; None = always
    max_tasks_per_tick: int = 20
    max_concurrent: int = 4
    freshness_window: float = 3600.0 * 6               # re-search a category at most every 6h
    model_available: bool = True
    exploration_rate: float = 0.30                      # initial epsilon
    error_backoff_base: float = 600.0


class DiscoveryScheduler:
    """Dynamic, history-driven discovery scheduler."""

    def __init__(self, memory=None, generator: Optional[SearchStrategyGenerator] = None,
                 config: Optional[SchedulerConfig] = None):
        self.memory = memory
        self.generator = generator or SearchStrategyGenerator()
        self.config = config or SchedulerConfig()
        self._states: Dict[str, SourceState] = {}
        self._category_last_searched: Dict[str, float] = {}
        self._tick_count = 0

    # ── state helpers ────────────────────────────────────────────
    def _state(self, source: str) -> SourceState:
        st = self._states.get(source)
        if st is None:
            st = SourceState(name=source)
            self._states[source] = st
        return st

    def _in_working_hours(self, now: float) -> bool:
        wh = self.config.working_hours
        if not wh:
            return True
        local_hour = time.localtime(now).tm_hour
        start, end = wh
        if start <= end:
            return start <= local_hour < end
        # wrap-around (e.g. 22..6)
        return local_hour >= start or local_hour < end

    # ── historical performance reads (deterministic) ────────────
    def _source_quality(self, source: str) -> Tuple[float, float]:
        """Return (reliability 0..1, avg_revenue) for a source from memory."""
        if self.memory is None:
            return (0.5, 0.0)
        rep = self.memory.get_platform_reputation(source)
        success = int(rep.get("success", 0) or 0)
        total = int(rep.get("total", 0) or 0)
        avg_rev = float(rep.get("avg_revenue", 0.0) or 0.0)
        reliability = (success / total) if total else 0.5
        return reliability, avg_rev

    def _category_profit(self, category: str) -> float:
        """Recent profitability of a category (success_rate * avg_revenue), normalized-ish."""
        if self.memory is None:
            return 0.0
        h = self.memory.get_category_history(category)
        sr = h.get("success_rate", 0.0) or 0.0
        rev = h.get("avg_revenue", 0.0) or 0.0
        # recency weight: confidence scales the signal
        conf = h.get("confidence", 0.0) or 0.0
        return sr * (1.0 + min(rev, 200.0) / 100.0) * (0.4 + 0.6 * conf)

    # ── dynamic interval + priority ──────────────────────────────
    def _update_source_timing(self, source: str, now: float) -> None:
        st = self._state(source)
        rel, avg_rev = self._source_quality(source)
        # Reliable + profitable -> search more often (shorter interval), higher priority.
        if rel >= 0.6 and avg_rev > 0:
            st.interval = max(MIN_INTERVAL, BASE_INTERVAL * EXPLOIT_INTERVAL_MULT)
            st.priority = 1.0 + min(rel, 1.0) + min(avg_rev / 100.0, 1.0)
        elif rel < 0.3 or (st.yield_count > 5 and st.yield_count * 0.1 > st.success_count + 1):
            # low reliability OR many listings, almost no success -> reduce.
            st.interval = min(MAX_INTERVAL, BASE_INTERVAL * REDUCE_INTERVAL_MULT)
            st.priority = max(0.2, rel)
        else:
            st.interval = BASE_INTERVAL
            st.priority = 0.5 + rel * 0.5

    # ── core selection ───────────────────────────────────────────
    def select_tasks(self, sources: List[str], now: Optional[float] = None) -> List[DiscoveryTask]:
        now = now or time.time()
        self._tick_count += 1
        tasks: List[DiscoveryTask] = []

        if not self._in_working_hours(now):
            return []  # outside configured working hours -> no discovery

        # Refresh per-source timing from history.
        for src in sources:
            self._update_source_timing(src, now)

        # Build candidate strategies from memory-informed generation.
        successful_categories = self._profitable_categories()
        successful_terms = self.memory.get_successful_search_terms(20) if self.memory else []
        failed_terms = self.memory.get_failed_search_terms(20) if self.memory else []
        strategies = self.generator.generate(
            known_skills=self._known_skills(),
            successful_categories=successful_categories,
            preferences=self._user_preferences(),
            successful_terms=successful_terms,
            failed_terms=failed_terms,
            sources=sources,
            memory=self.memory,
        )
        # Separate exploit vs explore strategies.
        exploit, explore = [], []
        for s in strategies:
            if s.origin in ("PAST_SUCCESS_TERM", "HISTORICAL_CATEGORY", "SKILL", "USER_PREFERENCE"):
                exploit.append(s)
            else:
                explore.append(s)
        # If model unavailable, drop LLM-folded suggestions (they live as USER_PREFERENCE here too,
        # but the scheduler treats non-core origins that need a model as exploration to skip).
        if not self.config.model_available:
            explore = [s for s in explore if s.origin != "EMERGING" or True]  # EMERGING is curated, keep
            # Remove any strategy whose query looks model-derived and model is off: keep curated only.
            explore = [s for s in explore if s.origin in ("EMERGING", "EXPLORATION", "PLATFORM_TERM")]

        # Keep NOVEL/under-tried strategies explorable: pull them from memory so historical
        # performance (even if a novel strategy looked weak once) never permanently suppresses
        # a fresh search. The exploration floor below guarantees they get a slot. Fail-safe:
        # only used if the memory backend actually implements explore_search_strategies().
        if self.memory and hasattr(self.memory, "explore_search_strategies"):
            try:
                for ns in self.memory.explore_search_strategies(10):
                    explore.append(SearchStrategy(
                        strategy_id=ns["strategy_id"], origin=ns.get("origin") or "EXPLORATION",
                        query=ns["query"], categories=[], source="",
                        created_at=ns.get("last_used", 0.0)))
            except Exception:
                pass

        # Decide exploration budget for this tick (epsilon-greedy + floor).
        epsilon = max(EXPLORATION_FLOOR, self.config.exploration_rate)
        # Exploration budget: at least the floor fraction, scaled by epsilon.
        floor_count = max(1, int(math.ceil(self.config.max_tasks_per_tick * EXPLORATION_FLOOR)))
        budget = max(floor_count, int(math.ceil(self.config.max_tasks_per_tick * epsilon)))

        # 1) Exploration tasks first, CAPPED at the exploration budget (so exploitation still runs).
        for s in explore:
            if len([t for t in tasks if t.is_exploration]) >= budget:
                break
            if len(tasks) >= self.config.max_tasks_per_tick:
                break
            src = s.source or (sources[0] if sources else "web")
            if not self._can_run(src, now):
                continue
            cat = (s.categories[0] if s.categories else "")
            if cat and not self._category_fresh(cat, now):
                continue
            tasks.append(DiscoveryTask(source=src, strategy=s, category=cat,
                                       priority=0.6, is_exploration=True,
                                       reason=f"explore:{s.origin}"))

        # 2) Exploitation tasks (known winners), up to remaining slots.
        remaining = self.config.max_tasks_per_tick - len(tasks)
        # Sort exploit strategies by source priority (reliable+profitable first).
        def _prio(st: SearchStrategy):
            return self._state(st.source or sources[0] if sources else "web").priority
        for s in sorted(exploit, key=_prio, reverse=True):
            if len(tasks) >= self.config.max_tasks_per_tick:
                break
            src = s.source or (sources[0] if sources else "web")
            if not self._can_run(src, now):
                continue
            cat = (s.categories[0] if s.categories else "")
            if cat and not self._category_fresh(cat, now):
                continue
            tasks.append(DiscoveryTask(source=src, strategy=s, category=cat,
                                       priority=_prio(s), is_exploration=False,
                                       reason=f"exploit:{s.origin}"))

        # Ensure exploration floor: if we ended with fewer than floor exploration tasks
        # (e.g., not enough distinct explore strategies), that is acceptable; but if NONE and
        # exploit filled everything, inject floor exploration from the explore pool.
        explo_count = sum(1 for t in tasks if t.is_exploration)
        if explo_count < floor_count:
            for s in explore:
                if sum(1 for t in tasks if t.is_exploration) >= floor_count:
                    break
                if len(tasks) >= self.config.max_tasks_per_tick:
                    break
                src = s.source or (sources[0] if sources else "web")
                if self._can_run(src, now):
                    tasks.append(DiscoveryTask(source=src, strategy=s,
                                               category=s.categories[0] if s.categories else "",
                                               priority=0.6, is_exploration=True,
                                               reason=f"floor:{s.origin}"))
        return tasks

    def _can_run(self, source: str, now: float) -> bool:
        st = self._state(source)
        if st.is_suspended(now):
            return False
        if (now - st.last_run) < st.interval:
            return False
        return True

    def _category_fresh(self, category: str, now: float) -> bool:
        last = self._category_last_searched.get(category, 0.0)
        return (now - last) >= self.config.freshness_window

    def _profitable_categories(self) -> List[str]:
        # Pull categories with decent recent profitability from memory.
        if self.memory is None:
            return []
        try:
            cats = self.memory.compute_all_metrics("category") if hasattr(self.memory, "compute_all_metrics") else []
            profitable = [m.value for m in cats if (m.success_rate or 0) >= 0.5 and (m.sample_size or 0) >= 2]
            return profitable[:15]
        except Exception:
            return []

    def _known_skills(self) -> List[str]:
        # Lightweight skill seed; in production this comes from config / discovered task types.
        if self.memory is None:
            return ["python", "writing", "data"]
        try:
            tts = self.memory.compute_all_metrics("task_type") if hasattr(self.memory, "compute_all_metrics") else []
            return [m.value for m in tts if (m.success_rate or 0) >= 0.5][:15] or ["python", "writing"]
        except Exception:
            return ["python", "writing"]

    def _user_preferences(self) -> List[str]:
        # Pulled from conversational_memory / config in production; empty default is fine.
        return []

    # ── outcome recording ────────────────────────────────────────
    def record_outcome(self, source: str, strategy_id: str, *, success: bool = False,
                       revenue: float = 0.0, error: bool = False, now: Optional[float] = None) -> None:
        now = now or time.time()
        st = self._state(source)
        st.last_run = now
        if error:
            st.error_count += 1
            st.suspended_until = now + st.backoff_seconds(self.config.error_backoff_base)
        else:
            st.error_count = max(0, st.error_count - 1)  # recover
            st.suspended_until = 0.0
            if success:
                st.success_count += 1
            st.yield_count += 1
        if self.memory and strategy_id:
            self.memory.record_strategy_outcome(strategy_id, success, revenue)

    def mark_searched(self, category: str, now: Optional[float] = None) -> None:
        self._category_last_searched[category] = now or time.time()

    # ── execution (validated provider interface ONLY) ───────────
    def run_task(self, task: DiscoveryTask, discover_fn,
                 now: Optional[float] = None) -> Tuple[List, str]:
        """Execute ONE discovery task through a VALIDATED provider interface.

        `discover_fn(source_name, strategy) -> List[Opportunity]` is injected by the pipeline
        (e.g. DiscoveryEngine per-source discover). The LLM is NEVER given an external action here.
        Returns (opportunities, error). Each opp is tagged with the strategy provenance so we can
        later learn which search strategies produce profitable work.
        """
        now = now or time.time()
        src = task.source
        try:
            found = discover_fn(src, task.strategy) or []
        except Exception as e:  # isolate one bad source/task
            self.record_outcome(src, task.strategy.strategy_id if task.strategy else "",
                                error=True, now=now)
            return [], str(e)
        # Tag provenance + record strategy usage (learning link).
        for o in found:
            tag = task.strategy.provenance_tag() if task.strategy else ""
            if tag:
                o.provenance = (f"{o.provenance}::{tag}") if o.provenance else tag
            if task.category:
                o.category = o.category or task.category
        if self.memory and task.strategy:
            self.memory.record_search_strategy(
                task.strategy.strategy_id, task.strategy.origin, task.strategy.query,
                task.strategy.categories, task.strategy.source or src)
        if task.category:
            self.mark_searched(task.category, now)
        self.record_outcome(src, task.strategy.strategy_id if task.strategy else "",
                            success=bool(found), revenue=0.0, now=now)
        return found, ""

    def tick(self, discover_fn, sources: Optional[List[str]] = None,
             now: Optional[float] = None) -> dict:
        """Run one discovery cycle. Returns a stats dict; discovered opps carry strategy provenance.

        `discover_fn(source_name, strategy) -> List[Opportunity]` is the ONLY external entry point
        (validated provider interface). Deterministic; the LLM is not invoked here.
        """
        now = now or time.time()
        srcs = sources or list(self._states.keys()) or ["web"]
        tasks = self.select_tasks(srcs, now=now)
        all_opps: List = []
        errors: Dict[str, str] = {}
        for t in tasks:
            opps, err = self.run_task(t, discover_fn, now=now)
            all_opps.extend(opps)
            if err:
                errors[t.source] = err
        return {
            "tasks": len(tasks),
            "opportunities": len(all_opps),
            "errors": errors,
            "exploration": sum(1 for t in tasks if t.is_exploration),
            "exploitation": sum(1 for t in tasks if not t.is_exploration),
        }
